import type { Metadata } from 'next';
import { Montserrat, Bonheur_Royale, Anton } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
});

const bonheurRoyale = Bonheur_Royale({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-bonheur',
});

const anton = Anton({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-anton',
});

export const metadata: Metadata = {
  title: 'My Portfolio',
  description: 'Generated by Latifahtul Khaerani',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={clsx(
          montserrat.variable,
          bonheurRoyale.variable,
          anton.variable,
          'antialiased'
        )}
      >
        {children}
      </body>
    </html>
  );
}
